name: 'Build libsame'

on:
  workflow_dispatch:

jobs:
  debug_build_with_gcc_static:
    name: Build debug static library using gcc
    runs-on: ubuntu-20.04

    steps:
      - name: Install build dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential ninja-build re2c cmake
          version: 1.0

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Configure project
        run: |
          cd ${GITHUB_WORKSPACE}
          cmake -S . -B build -G Ninja -DLIBSAME_STATIC_LIBRARY:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Debug

      - name: Build project
        run: |
          cd ${GITHUB_WORKSPACE}/build
          ninja -v

  release_build_with_gcc:
    name: Build release static library using gcc
    runs-on: ubuntu-20.04

    steps:
      - name: Install build dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: build-essential ninja-build re2c cmake
          version: 1.0

      - name: Clone repository
        uses: actions/checkout@v4

      - name: Configure project
        run: |
          cd ${GITHUB_WORKSPACE}
          cmake -S . -B build -G Ninja -DLIBSAME_STATIC_LIBRARY:BOOL=ON -DCMAKE_BUILD_TYPE:STRING=Release

      - name: Build project
        run: |
          cd ${GITHUB_WORKSPACE}/build
          ninja -v
